### ISSUE TITLE
Bug: workspaces stats endpoint for workspaces should return stars and forks for the given time range.

### ISSUE THREAD

**Issue by nickytonline** [open-sauced/api#551] opened 2024-02-08 21:20 UTC
Currently the [/v2/workspaces/{id}/stats](https://beta.api.opensauced.pizza/#/Workspaces%20stats%20service/getWorkspaceStatsForUser) endpoint returns stars and forks as part of the payload, but they are for the entire lifetime of the associated repositories.

```json
{
  "pull_requests": {
    "opened": 4,
    "merged": 1,
    "velocity": 2
  },
  "issues": {
    "opened": 4,
    "closed": 1,
    "velocity": 2
  },
  "repos": {
    "stars": 1234,
    "forks": 987,
    "health": 9
  }
}
```

It should return the stars and forks for the given day range.

**Comment by jpmcb** [comment] 2024-02-20 21:45
Duplicate of: https://github.com/open-sauced/api/issues/530

Closed by: https://github.com/open-sauced/api/pull/582

**Closed by jpmcb** 2024-02-20 21:45 UTC
Labels: 🐛 bug, core team work
